#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (file_exists($__composer_autoload_path = __DIR__ . '/vendor/autoload.php')) {
    require $__composer_autoload_path;
} else {
    fwrite(
        STDERR,
        'Composer autoload file not found. Run "composer install" first.' . PHP_EOL
    );
    exit(1);
}

$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
));
